# Default values for nexus.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

environment: test

strategy:
  type: Recreate
restartPolicy: Always

image:
  repository: registry.molgenis.org
  name: molgenis/molgenis-frontend
  tag: latest
  pullPolicy: Always

service:
  name: molgenis-frontend
  type: ClusterIP
  port: 80

proxy:
  backend:
    url: http://master-molgenis.molgenis-abcde.svc:8080/
  custom:
  - url: https://unpkg.com/@mswertz
    path: experimental/@mswertz
#
# You can define custom urls you want to proxy on a certain path.
# This needs to be done in the values.yaml at this moment. In the questions.yaml you can specify only 1.
#
#  custom:
#  - url: https://my-not-so-great-app
#    path: my-not-so-great-app

ingress:
  enabled: true
  path: /

resources: {}

nodeSelector:
  deployPod: "true"

tolerations: []

affinity: {}
