elasticsearch:
  image: "docker.elastic.co/elasticsearch/elasticsearch-oss"
  esJavaOpts: "-Xmx2560m -Xms2560m"
  resources:
    requests:
      cpu: "1000m"
      memory: "3Gi"
    limits:
      cpu: "1000m"
      memory: "3Gi"
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: "nginx"
      nginx.ingress.kubernetes.io/whitelist-source-range: 195.169.22.0/23
      nginx.ingress.kubernetes.io/proxy-body-size: 10m
    paths: /
  extraEnvs:
    - name: ELASTIC_PASSWORD
      valueFrom:
        secretKeyRef:
          name: "elastic-credentials"
          key: password
    - name: ELASTIC_USERNAME
      valueFrom:
        secretKeyRef:
          name: "elastic-credentials"
          key: username
  authentication:
    username: xxxx
    password: xxxx
kibana:
  image: "docker.elastic.co/kibana/kibana-oss"
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: "nginx"
      nginx.ingress.kubernetes.io/auth-signin: https://oauth2.molgenis.org/oauth2/start?rd=https://$host$request_uri
      nginx.ingress.kubernetes.io/auth-url: https://oauth2.molgenis.org/oauth2/auth
    path: /
  extraEnvs:
    - name: 'ELASTICSEARCH_USERNAME'
      valueFrom:
        secretKeyRef:
          name: "elastic-credentials"
          key: username
    - name: 'ELASTICSEARCH_PASSWORD'
      valueFrom:
        secretKeyRef:
          name: "elastic-credentials"
          key: password
elasticsearch-curator:
  cronjob:
    schedule: "0 13 * * 6"
  dryrun: true
  configMaps:
    action_file_yml: |-
      ---
      actions:
        1:
          action: delete_indices
          description: "Clean up ES by deleting old indices every saturday"
          options:
            timeout_override:
            continue_if_exception: False
            disable_action: False
            ignore_empty_list: True
          filters:
          - filtertype: age
            source: filebeat-*-elasticsearch-*
            direction: older
            timestring: '%Y.%m.%d'
            unit: days
            unit_count: 14
            exclude: False
          - filtertype: age
            source: filebeat-*-postgresql-*
            direction: older
            timestring: '%Y.%m.%d'
            unit: days
            unit_count: 14
            exclude: False
          - filtertype: age
            source: filebeat-*-rancher-*
            direction: older
            timestring: '%Y.%m.%d'
            unit: days
            unit_count: 14
            exclude: False
          - filtertype: age
            source: filebeat-*-rancher-elasticsearch-*
            direction: older
            timestring: '%Y.%m.%d'
            unit: days
            unit_count: 14
            exclude: False
          - filtertype: age
            source: filebeat-*-rancher-etcd-*
            direction: older
            timestring: '%Y.%m.%d'
            unit: days
            unit_count: 14
            exclude: False
          - filtertype: age
            source: filebeat-*-rancher-molgenis-*
            direction: older
            timestring: '%Y.%m.%d'
            unit: days
            unit_count: 14
            exclude: False
          - filtertype: age
            source: filebeat-*-rancher-other-*
            direction: older
            timestring: '%Y.%m.%d'
            unit: days
            unit_count: 14
            exclude: False
          - filtertype: age
            source: filebeat-*-system-*
            direction: older
            timestring: '%Y.%m.%d'
            unit: days
            unit_count: 14
            exclude: False
          - filtertype: age
            source: filebeat-*-tomcat-*
            direction: older
            timestring: '%Y.%m.%d'
            unit: days
            unit_count: 14
            exclude: False
          - filtertype: age
            source: metricbeat-*
            direction: older
            timestring: '%Y.%m.%d'
            unit: days
            unit_count: 14
            exclude: False
          - filtertype: empty
            exclude: False
    # Having config_yaml WILL override the other config
    config_yml: |-
      ---
      client:
        hosts:
          - elasticsearch-master.host
        port: 9200
        # url_prefix:
        # use_ssl: True
        # certificate:
        # client_cert:
        # client_key:
        # ssl_no_validate: True
        # http_auth:
        # timeout: 30
        # master_only: False
      # logging:
      #   loglevel: INFO
      #   logfile:
      #   logformat: default
      #   blacklist: ['elasticsearch', 'urllib3']
