apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: molgenis-prometheus-prod
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: get-targets
            image: rancher/cli2:v2.2.0
            #image: busybox
            envFrom:
            - secretRef:
                name: molgenis-prometheus-github-token
            # volumeMounts:
            # - name: mount-secret-cli
            #   mountPath: "/root/.rancher/"
            #   readOnly: true
            command: ["/bin/sh"]
            #args: ["-c", "echo ${GITHUBTOKEN}"]
            args: ["-c", "apk add curl bash && curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.15.2/bin/linux/amd64/kubectl && chmod +x kubectl && mv kubectl /usr/local/bin/kubectl && TOKEN=$(cat /run/secrets/kubernetes.io/serviceaccount/token) && wget ${GITHUBTOKEN}@raw.githubusercontent.com/christianhilbrands/molgenis-ops-helm/feat/production-prometheus/charts/molgenis-prometheus-prod/scripts/k8sScrapeTargetExtractor.sh -O k8sScrapeTargetExtractor.sh && chmod +x k8sScrapeTargetExtractor.sh && bash k8sScrapeTargetExtractor.sh ${GITHUBTOKEN} && rm -rf /mnt/k8sScrapeTargetExtractor.sh"]
          serviceAccountName: update-configmap-bot
          # volumes:
          #   - name: mount-secret-cli
          #     secret:
          #       secretName: molgenis-prometheus-github-token
          restartPolicy: OnFailure