apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: molgenis-prometheus-prod
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: get-targets
            image: rancher/cli2:v2.2.0
            #image: busybox
            envFrom:
            - secretRef:
                name: molgenis-prometheus-github-token
            volumeMounts:
            - name: mount-secret-cli
              mountPath: "/config/.rancher/"
              readOnly: true
            command: ["/bin/sh"]
            #args: ["-c", "echo ${GITHUBTOKEN}"]
            args: ["-c", "ls -al /mnt","mv /config/.rancher/cli2.json /mnt/.rancher/ && wget ${GITHUBTOKEN}@raw.githubusercontent.com/christianhilbrands/molgenis-ops-helm/feat/production-prometheus/charts/molgenis-prometheus-prod/scripts/k8sScrapeTargetExtractor.sh && chmod +x k8sScrapeTargetExtractor.sh && ./k8sScrapeTargetExtractor.sh ${GITHUBTOKEN} && rm -rf k8sScrapeTargetExtractor.sh"]
          volumes:
            - name: mount-secret-cli
              secret:
                secretName: molgenis-prometheus-github-token
          restartPolicy: OnFailure