apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: molgenis-prometheus-prod
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: get-targets
            image: rancher/cli2:v2.2.0
            envFrom:
            - secretRef:
                name: molgenis-prometheus-github-token
            args:
            - /usr/bin/wget
            - -c0
            - /home/rancher-cli
            - ${GITHUBTOKEN}@raw.githubusercontent.com/christianhilbrands/molgenis-ops-helm/feat/production-prometheus/charts/molgenis-prometheus-prod/scripts/k8sScrapeTargetExtractor.sh
          restartPolicy: OnFailure