apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: hello
spec:
  schedule: "30 5 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: targetsRefresher
            image: rancher/cli2:v2.2.0
            args:
            - /bin/sh
            - -c
            - date; echo "Hello, World!"
          restartPolicy: OnFailure