apiVersion: v1
kind: ConfigMap
metadata:
  name: targets-configmap
data:
  masterTargetsAcquired.yml: |
    #- job_name: 'masterBranchNodes'
    #  static_configs:
    - targets: ['molgenis117.gcc.rug.nl:9100'] 
      labels: 
        project: "GCC test server" 
        branch: "master" 
        dtap: "test"
  20TargetsAcquired.yml: |
    #job
  10TargetsAcquired.yml: |
    #job
  01TargetsAcquired.yml: |
    #job